version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/Blog_Project/Travis/build/
  overwrite: true
permissions:
- object: /
  pattern: "**"
  owner: ubuntu
  group: ubuntu
hooks:
  AfterInstall:
  - location: execute-deploy.sh
    timeout: 180
    runas: ubuntu
   
