management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true  

spring.devtools.add-properties: true

spring:
  config:    activate:      on-profile:      - local
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: 
    password: 
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
#      update, none, create가 될 수 있다. create는 계속 새로 테이블을 생성함을 의미. 기존에 있으면 Drop함
#         최초에만 create하고, 후에는 update로 바꿔야 한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        테이블 피드를 생성할 때 유저가 설정한 그대로 생성
      use-new-id-generator-mappings: false
#      false->jpa가 사용하는 기본 넘버링 사용 X , True -> 개발자가 지정.
    show-sql: false
#    콘솔에 mysql 표시
    properties:
      hibernate.format_sql: true
#표시된 텍스트들 이쁘게 정렬 ㅋㅋ
  jackson:
    serialization:
      fail-on-empty-beans: false    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul      


cos:
  key: 


